package edu.stupaysys.po;

public class Bundle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer bundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundlename
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String bundlename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundlevalidtime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer bundlevalidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundlestate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer bundlestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundleprice
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Double bundleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bundle.bundleinfo
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String bundleinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundleid
     *
     * @return the value of bundle.bundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getBundleid() {
        return bundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundleid
     *
     * @param bundleid the value for bundle.bundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundleid(Integer bundleid) {
        this.bundleid = bundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundlename
     *
     * @return the value of bundle.bundlename
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getBundlename() {
        return bundlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundlename
     *
     * @param bundlename the value for bundle.bundlename
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundlename(String bundlename) {
        this.bundlename = bundlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundlevalidtime
     *
     * @return the value of bundle.bundlevalidtime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getBundlevalidtime() {
        return bundlevalidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundlevalidtime
     *
     * @param bundlevalidtime the value for bundle.bundlevalidtime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundlevalidtime(Integer bundlevalidtime) {
        this.bundlevalidtime = bundlevalidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundlestate
     *
     * @return the value of bundle.bundlestate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getBundlestate() {
        return bundlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundlestate
     *
     * @param bundlestate the value for bundle.bundlestate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundlestate(Integer bundlestate) {
        this.bundlestate = bundlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundleprice
     *
     * @return the value of bundle.bundleprice
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Double getBundleprice() {
        return bundleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundleprice
     *
     * @param bundleprice the value for bundle.bundleprice
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundleprice(Double bundleprice) {
        this.bundleprice = bundleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bundle.bundleinfo
     *
     * @return the value of bundle.bundleinfo
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getBundleinfo() {
        return bundleinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bundle.bundleinfo
     *
     * @param bundleinfo the value for bundle.bundleinfo
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setBundleinfo(String bundleinfo) {
        this.bundleinfo = bundleinfo;
    }
}