package edu.stupaysys.po;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custname
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String custname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custcreateid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer custcreateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custdor
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String custdor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custphone
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String custphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custcreatedate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Date custcreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer custbundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custnetvaliddate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Date custnetvaliddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custid
     *
     * @return the value of customer.custid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custid
     *
     * @param custid the value for customer.custid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custname
     *
     * @return the value of customer.custname
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custname
     *
     * @param custname the value for customer.custname
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustname(String custname) {
        this.custname = custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custcreateid
     *
     * @return the value of customer.custcreateid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getCustcreateid() {
        return custcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custcreateid
     *
     * @param custcreateid the value for customer.custcreateid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustcreateid(Integer custcreateid) {
        this.custcreateid = custcreateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custdor
     *
     * @return the value of customer.custdor
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getCustdor() {
        return custdor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custdor
     *
     * @param custdor the value for customer.custdor
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustdor(String custdor) {
        this.custdor = custdor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custphone
     *
     * @return the value of customer.custphone
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getCustphone() {
        return custphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custphone
     *
     * @param custphone the value for customer.custphone
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustphone(String custphone) {
        this.custphone = custphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custcreatedate
     *
     * @return the value of customer.custcreatedate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Date getCustcreatedate() {
        return custcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custcreatedate
     *
     * @param custcreatedate the value for customer.custcreatedate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustcreatedate(Date custcreatedate) {
        this.custcreatedate = custcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custbundleid
     *
     * @return the value of customer.custbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getCustbundleid() {
        return custbundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custbundleid
     *
     * @param custbundleid the value for customer.custbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustbundleid(Integer custbundleid) {
        this.custbundleid = custbundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custnetvaliddate
     *
     * @return the value of customer.custnetvaliddate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Date getCustnetvaliddate() {
        return custnetvaliddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custnetvaliddate
     *
     * @param custnetvaliddate the value for customer.custnetvaliddate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setCustnetvaliddate(Date custnetvaliddate) {
        this.custnetvaliddate = custnetvaliddate;
    }
}