package edu.stupaysys.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCustidIsNull() {
            addCriterion("custid is null");
            return (Criteria) this;
        }

        public Criteria andCustidIsNotNull() {
            addCriterion("custid is not null");
            return (Criteria) this;
        }

        public Criteria andCustidEqualTo(Integer value) {
            addCriterion("custid =", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotEqualTo(Integer value) {
            addCriterion("custid <>", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidGreaterThan(Integer value) {
            addCriterion("custid >", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidGreaterThanOrEqualTo(Integer value) {
            addCriterion("custid >=", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidLessThan(Integer value) {
            addCriterion("custid <", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidLessThanOrEqualTo(Integer value) {
            addCriterion("custid <=", value, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidIn(List<Integer> values) {
            addCriterion("custid in", values, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotIn(List<Integer> values) {
            addCriterion("custid not in", values, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidBetween(Integer value1, Integer value2) {
            addCriterion("custid between", value1, value2, "custid");
            return (Criteria) this;
        }

        public Criteria andCustidNotBetween(Integer value1, Integer value2) {
            addCriterion("custid not between", value1, value2, "custid");
            return (Criteria) this;
        }

        public Criteria andCustnameIsNull() {
            addCriterion("custname is null");
            return (Criteria) this;
        }

        public Criteria andCustnameIsNotNull() {
            addCriterion("custname is not null");
            return (Criteria) this;
        }

        public Criteria andCustnameEqualTo(String value) {
            addCriterion("custname =", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotEqualTo(String value) {
            addCriterion("custname <>", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameGreaterThan(String value) {
            addCriterion("custname >", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameGreaterThanOrEqualTo(String value) {
            addCriterion("custname >=", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLessThan(String value) {
            addCriterion("custname <", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLessThanOrEqualTo(String value) {
            addCriterion("custname <=", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameLike(String value) {
            addCriterion("custname like", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotLike(String value) {
            addCriterion("custname not like", value, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameIn(List<String> values) {
            addCriterion("custname in", values, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotIn(List<String> values) {
            addCriterion("custname not in", values, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameBetween(String value1, String value2) {
            addCriterion("custname between", value1, value2, "custname");
            return (Criteria) this;
        }

        public Criteria andCustnameNotBetween(String value1, String value2) {
            addCriterion("custname not between", value1, value2, "custname");
            return (Criteria) this;
        }

        public Criteria andCustcreateidIsNull() {
            addCriterion("custcreateid is null");
            return (Criteria) this;
        }

        public Criteria andCustcreateidIsNotNull() {
            addCriterion("custcreateid is not null");
            return (Criteria) this;
        }

        public Criteria andCustcreateidEqualTo(Integer value) {
            addCriterion("custcreateid =", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidNotEqualTo(Integer value) {
            addCriterion("custcreateid <>", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidGreaterThan(Integer value) {
            addCriterion("custcreateid >", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidGreaterThanOrEqualTo(Integer value) {
            addCriterion("custcreateid >=", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidLessThan(Integer value) {
            addCriterion("custcreateid <", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidLessThanOrEqualTo(Integer value) {
            addCriterion("custcreateid <=", value, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidIn(List<Integer> values) {
            addCriterion("custcreateid in", values, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidNotIn(List<Integer> values) {
            addCriterion("custcreateid not in", values, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidBetween(Integer value1, Integer value2) {
            addCriterion("custcreateid between", value1, value2, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustcreateidNotBetween(Integer value1, Integer value2) {
            addCriterion("custcreateid not between", value1, value2, "custcreateid");
            return (Criteria) this;
        }

        public Criteria andCustdorIsNull() {
            addCriterion("custdor is null");
            return (Criteria) this;
        }

        public Criteria andCustdorIsNotNull() {
            addCriterion("custdor is not null");
            return (Criteria) this;
        }

        public Criteria andCustdorEqualTo(String value) {
            addCriterion("custdor =", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorNotEqualTo(String value) {
            addCriterion("custdor <>", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorGreaterThan(String value) {
            addCriterion("custdor >", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorGreaterThanOrEqualTo(String value) {
            addCriterion("custdor >=", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorLessThan(String value) {
            addCriterion("custdor <", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorLessThanOrEqualTo(String value) {
            addCriterion("custdor <=", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorLike(String value) {
            addCriterion("custdor like", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorNotLike(String value) {
            addCriterion("custdor not like", value, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorIn(List<String> values) {
            addCriterion("custdor in", values, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorNotIn(List<String> values) {
            addCriterion("custdor not in", values, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorBetween(String value1, String value2) {
            addCriterion("custdor between", value1, value2, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustdorNotBetween(String value1, String value2) {
            addCriterion("custdor not between", value1, value2, "custdor");
            return (Criteria) this;
        }

        public Criteria andCustphoneIsNull() {
            addCriterion("custphone is null");
            return (Criteria) this;
        }

        public Criteria andCustphoneIsNotNull() {
            addCriterion("custphone is not null");
            return (Criteria) this;
        }

        public Criteria andCustphoneEqualTo(String value) {
            addCriterion("custphone =", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneNotEqualTo(String value) {
            addCriterion("custphone <>", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneGreaterThan(String value) {
            addCriterion("custphone >", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneGreaterThanOrEqualTo(String value) {
            addCriterion("custphone >=", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneLessThan(String value) {
            addCriterion("custphone <", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneLessThanOrEqualTo(String value) {
            addCriterion("custphone <=", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneLike(String value) {
            addCriterion("custphone like", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneNotLike(String value) {
            addCriterion("custphone not like", value, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneIn(List<String> values) {
            addCriterion("custphone in", values, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneNotIn(List<String> values) {
            addCriterion("custphone not in", values, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneBetween(String value1, String value2) {
            addCriterion("custphone between", value1, value2, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustphoneNotBetween(String value1, String value2) {
            addCriterion("custphone not between", value1, value2, "custphone");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateIsNull() {
            addCriterion("custcreatedate is null");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateIsNotNull() {
            addCriterion("custcreatedate is not null");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("custcreatedate =", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("custcreatedate <>", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("custcreatedate >", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("custcreatedate >=", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateLessThan(Date value) {
            addCriterionForJDBCDate("custcreatedate <", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("custcreatedate <=", value, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateIn(List<Date> values) {
            addCriterionForJDBCDate("custcreatedate in", values, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateNotIn(List<Date> values) {
            addCriterionForJDBCDate("custcreatedate not in", values, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("custcreatedate between", value1, value2, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustcreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("custcreatedate not between", value1, value2, "custcreatedate");
            return (Criteria) this;
        }

        public Criteria andCustbundleidIsNull() {
            addCriterion("custbundleid is null");
            return (Criteria) this;
        }

        public Criteria andCustbundleidIsNotNull() {
            addCriterion("custbundleid is not null");
            return (Criteria) this;
        }

        public Criteria andCustbundleidEqualTo(Integer value) {
            addCriterion("custbundleid =", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidNotEqualTo(Integer value) {
            addCriterion("custbundleid <>", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidGreaterThan(Integer value) {
            addCriterion("custbundleid >", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("custbundleid >=", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidLessThan(Integer value) {
            addCriterion("custbundleid <", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidLessThanOrEqualTo(Integer value) {
            addCriterion("custbundleid <=", value, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidIn(List<Integer> values) {
            addCriterion("custbundleid in", values, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidNotIn(List<Integer> values) {
            addCriterion("custbundleid not in", values, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidBetween(Integer value1, Integer value2) {
            addCriterion("custbundleid between", value1, value2, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustbundleidNotBetween(Integer value1, Integer value2) {
            addCriterion("custbundleid not between", value1, value2, "custbundleid");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateIsNull() {
            addCriterion("custnetvaliddate is null");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateIsNotNull() {
            addCriterion("custnetvaliddate is not null");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateEqualTo(Date value) {
            addCriterion("custnetvaliddate =", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateNotEqualTo(Date value) {
            addCriterion("custnetvaliddate <>", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateGreaterThan(Date value) {
            addCriterion("custnetvaliddate >", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateGreaterThanOrEqualTo(Date value) {
            addCriterion("custnetvaliddate >=", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateLessThan(Date value) {
            addCriterion("custnetvaliddate <", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateLessThanOrEqualTo(Date value) {
            addCriterion("custnetvaliddate <=", value, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateIn(List<Date> values) {
            addCriterion("custnetvaliddate in", values, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateNotIn(List<Date> values) {
            addCriterion("custnetvaliddate not in", values, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateBetween(Date value1, Date value2) {
            addCriterion("custnetvaliddate between", value1, value2, "custnetvaliddate");
            return (Criteria) this;
        }

        public Criteria andCustnetvaliddateNotBetween(Date value1, Date value2) {
            addCriterion("custnetvaliddate not between", value1, value2, "custnetvaliddate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 02 17:00:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}