package edu.stupaysys.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidIsNull() {
            addCriterion("ordercustid is null");
            return (Criteria) this;
        }

        public Criteria andOrdercustidIsNotNull() {
            addCriterion("ordercustid is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercustidEqualTo(Integer value) {
            addCriterion("ordercustid =", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidNotEqualTo(Integer value) {
            addCriterion("ordercustid <>", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidGreaterThan(Integer value) {
            addCriterion("ordercustid >", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordercustid >=", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidLessThan(Integer value) {
            addCriterion("ordercustid <", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidLessThanOrEqualTo(Integer value) {
            addCriterion("ordercustid <=", value, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidIn(List<Integer> values) {
            addCriterion("ordercustid in", values, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidNotIn(List<Integer> values) {
            addCriterion("ordercustid not in", values, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidBetween(Integer value1, Integer value2) {
            addCriterion("ordercustid between", value1, value2, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrdercustidNotBetween(Integer value1, Integer value2) {
            addCriterion("ordercustid not between", value1, value2, "ordercustid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidIsNull() {
            addCriterion("orderbundleid is null");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidIsNotNull() {
            addCriterion("orderbundleid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidEqualTo(Integer value) {
            addCriterion("orderbundleid =", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidNotEqualTo(Integer value) {
            addCriterion("orderbundleid <>", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidGreaterThan(Integer value) {
            addCriterion("orderbundleid >", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderbundleid >=", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidLessThan(Integer value) {
            addCriterion("orderbundleid <", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidLessThanOrEqualTo(Integer value) {
            addCriterion("orderbundleid <=", value, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidIn(List<Integer> values) {
            addCriterion("orderbundleid in", values, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidNotIn(List<Integer> values) {
            addCriterion("orderbundleid not in", values, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidBetween(Integer value1, Integer value2) {
            addCriterion("orderbundleid between", value1, value2, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrderbundleidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderbundleid not between", value1, value2, "orderbundleid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridIsNull() {
            addCriterion("ordercreateuserid is null");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridIsNotNull() {
            addCriterion("ordercreateuserid is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridEqualTo(Integer value) {
            addCriterion("ordercreateuserid =", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridNotEqualTo(Integer value) {
            addCriterion("ordercreateuserid <>", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridGreaterThan(Integer value) {
            addCriterion("ordercreateuserid >", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordercreateuserid >=", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridLessThan(Integer value) {
            addCriterion("ordercreateuserid <", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridLessThanOrEqualTo(Integer value) {
            addCriterion("ordercreateuserid <=", value, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridIn(List<Integer> values) {
            addCriterion("ordercreateuserid in", values, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridNotIn(List<Integer> values) {
            addCriterion("ordercreateuserid not in", values, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridBetween(Integer value1, Integer value2) {
            addCriterion("ordercreateuserid between", value1, value2, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreateuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("ordercreateuserid not between", value1, value2, "ordercreateuserid");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeIsNull() {
            addCriterion("ordercreatetime is null");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeIsNotNull() {
            addCriterion("ordercreatetime is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeEqualTo(Date value) {
            addCriterion("ordercreatetime =", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeNotEqualTo(Date value) {
            addCriterion("ordercreatetime <>", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeGreaterThan(Date value) {
            addCriterion("ordercreatetime >", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ordercreatetime >=", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeLessThan(Date value) {
            addCriterion("ordercreatetime <", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("ordercreatetime <=", value, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeIn(List<Date> values) {
            addCriterion("ordercreatetime in", values, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeNotIn(List<Date> values) {
            addCriterion("ordercreatetime not in", values, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeBetween(Date value1, Date value2) {
            addCriterion("ordercreatetime between", value1, value2, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrdercreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("ordercreatetime not between", value1, value2, "ordercreatetime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeIsNull() {
            addCriterion("orderpaytime is null");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeIsNotNull() {
            addCriterion("orderpaytime is not null");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeEqualTo(Date value) {
            addCriterion("orderpaytime =", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeNotEqualTo(Date value) {
            addCriterion("orderpaytime <>", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeGreaterThan(Date value) {
            addCriterion("orderpaytime >", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("orderpaytime >=", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeLessThan(Date value) {
            addCriterion("orderpaytime <", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeLessThanOrEqualTo(Date value) {
            addCriterion("orderpaytime <=", value, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeIn(List<Date> values) {
            addCriterion("orderpaytime in", values, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeNotIn(List<Date> values) {
            addCriterion("orderpaytime not in", values, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeBetween(Date value1, Date value2) {
            addCriterion("orderpaytime between", value1, value2, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderpaytimeNotBetween(Date value1, Date value2) {
            addCriterion("orderpaytime not between", value1, value2, "orderpaytime");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNull() {
            addCriterion("orderstate is null");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNotNull() {
            addCriterion("orderstate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstateEqualTo(Integer value) {
            addCriterion("orderstate =", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotEqualTo(Integer value) {
            addCriterion("orderstate <>", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThan(Integer value) {
            addCriterion("orderstate >", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderstate >=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThan(Integer value) {
            addCriterion("orderstate <", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThanOrEqualTo(Integer value) {
            addCriterion("orderstate <=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateIn(List<Integer> values) {
            addCriterion("orderstate in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotIn(List<Integer> values) {
            addCriterion("orderstate not in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateBetween(Integer value1, Integer value2) {
            addCriterion("orderstate between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotBetween(Integer value1, Integer value2) {
            addCriterion("orderstate not between", value1, value2, "orderstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 02 17:00:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}