package edu.stupaysys.po;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Order {
    @Override
	public String toString() {
		return "Order [orderid=" + orderid + ", ordercustid=" + ordercustid + ", orderbundleid=" + orderbundleid
				+ ", ordercreateuserid=" + ordercreateuserid + ", ordercreatetime=" + ordercreatetime
				+ ", orderpaytime=" + orderpaytime + ", orderstate=" + orderstate + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordercustid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer ordercustid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer orderbundleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordercreateuserid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer ordercreateuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordercreatetime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Date ordercreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderpaytime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
   
    private Date orderpaytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer orderstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderid
     *
     * @return the value of order.orderid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderid
     *
     * @param orderid the value for order.orderid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordercustid
     *
     * @return the value of order.ordercustid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getOrdercustid() {
        return ordercustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordercustid
     *
     * @param ordercustid the value for order.ordercustid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrdercustid(Integer ordercustid) {
        this.ordercustid = ordercustid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderbundleid
     *
     * @return the value of order.orderbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getOrderbundleid() {
        return orderbundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderbundleid
     *
     * @param orderbundleid the value for order.orderbundleid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderbundleid(Integer orderbundleid) {
        this.orderbundleid = orderbundleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordercreateuserid
     *
     * @return the value of order.ordercreateuserid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getOrdercreateuserid() {
        return ordercreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordercreateuserid
     *
     * @param ordercreateuserid the value for order.ordercreateuserid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrdercreateuserid(Integer ordercreateuserid) {
        this.ordercreateuserid = ordercreateuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordercreatetime
     *
     * @return the value of order.ordercreatetime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Date getOrdercreatetime() {
        return ordercreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordercreatetime
     *
     * @param ordercreatetime the value for order.ordercreatetime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrdercreatetime(Date ordercreatetime) {
        this.ordercreatetime = ordercreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderpaytime
     *
     * @return the value of order.orderpaytime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Date getOrderpaytime() {
        return orderpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderpaytime
     *
     * @param orderpaytime the value for order.orderpaytime
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderpaytime(Date orderpaytime) {
        this.orderpaytime = orderpaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderstate
     *
     * @return the value of order.orderstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderstate
     *
     * @param orderstate the value for order.orderstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setOrderstate(Integer orderstate) {
        this.orderstate = orderstate;
    }
}