package edu.stupaysys.po;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpassword
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String userpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userlimit
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String userlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    private String userstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpassword
     *
     * @return the value of userinfo.userpassword
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpassword
     *
     * @param userpassword the value for userinfo.userpassword
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userlimit
     *
     * @return the value of userinfo.userlimit
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getUserlimit() {
        return userlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userlimit
     *
     * @param userlimit the value for userinfo.userlimit
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setUserlimit(String userlimit) {
        this.userlimit = userlimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userstate
     *
     * @return the value of userinfo.userstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public String getUserstate() {
        return userstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userstate
     *
     * @param userstate the value for userinfo.userstate
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    public void setUserstate(String userstate) {
        this.userstate = userstate;
    }

	@Override
	public String toString() {
		return "User [userid=" + userid + ", username=" + username + ", userpassword=" + userpassword + ", userlimit="
				+ userlimit + ", userstate=" + userstate + "]";
	}
    
}