package edu.stupaysys.dao;

import edu.stupaysys.po.Bundle;
import edu.stupaysys.po.BundleExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BundleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    long countByExample(BundleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer bundleid);
    int deleteByExample(BundleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    int insert(Bundle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    int insertSelective(Bundle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    List<Bundle> selectByExample(BundleExample example);
    Bundle selectByPrimaryKey(Integer bundleid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bundle record, @Param("example") BundleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bundle
     *
     * @mbg.generated Mon Dec 02 17:00:21 CST 2019
     */
    int updateByExample(@Param("record") Bundle record, @Param("example") BundleExample example);
    int updateByPrimaryKey(Bundle bundle);
}